# Numpy

In [2]:
import numpy as np

In [59]:
np.array([2,3,2])

array([2, 3, 2])

In [60]:
np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [61]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
np.empty((5,5))

array([[2.37663529e-312, 2.41907520e-312, 2.33419537e-312,
        2.35541533e-312, 9.76118064e-313],
       [2.14321575e-312, 2.12199579e-312, 1.03977794e-312,
        8.70018275e-313, 2.33419537e-312],
       [9.76118064e-313, 2.05833592e-312, 2.12199579e-312,
        2.31297541e-312, 2.41907520e-312],
       [2.33419537e-312, 2.22809558e-312, 2.46151512e-312,
        1.03977794e-312, 1.10343781e-312],
       [8.48798317e-313, 9.33678148e-313, 8.70018275e-313,
        1.33511969e-306, 2.56765117e-312]])

In [65]:
a=np.arange(2,3)

In [66]:
a=np.arange(0,101,5)

In [67]:
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [32]:
type(a)

numpy.ndarray

In [68]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [69]:
b=a.reshape(3,7)

In [70]:
b

array([[  0,   5,  10,  15,  20,  25,  30],
       [ 35,  40,  45,  50,  55,  60,  65],
       [ 70,  75,  80,  85,  90,  95, 100]])

In [71]:
b.ravel()

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

# Transpose

In [72]:
b.transpose()

array([[  0,  35,  70],
       [  5,  40,  75],
       [ 10,  45,  80],
       [ 15,  50,  85],
       [ 20,  55,  90],
       [ 25,  60,  95],
       [ 30,  65, 100]])

In [73]:
b.T

array([[  0,  35,  70],
       [  5,  40,  75],
       [ 10,  45,  80],
       [ 15,  50,  85],
       [ 20,  55,  90],
       [ 25,  60,  95],
       [ 30,  65, 100]])

In [74]:
a=np.arange(1,13).reshape(3,4)

In [41]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:
a.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# jog biyog

In [75]:
b=np.arange(13,25).reshape(3,4)

In [76]:
print(b)

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [77]:
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [78]:
a+b

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [79]:
a-b

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [80]:
a*b

array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

In [81]:
a/b

array([[0.07692308, 0.14285714, 0.2       , 0.25      ],
       [0.29411765, 0.33333333, 0.36842105, 0.4       ],
       [0.42857143, 0.45454545, 0.47826087, 0.5       ]])

In [82]:
a**b

array([[          1,       16384,    14348907,           0],
       [-1564725563,  1159987200,   442181591,           0],
       [ 1914644777, -1304428544,  -122979837,           0]], dtype=int32)

In [83]:
np.add(a,b)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [51]:
np.max(a)

12

In [84]:
np.min(a)

1

In [85]:
np.sum(a)

78

In [54]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
a.argmax()

11

In [87]:
b.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [88]:
a[0,0]

1

In [89]:
a.argpartition(2)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [90]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# slicing

In [91]:
a[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
a[1:2]

array([[5, 6, 7, 8]])

In [93]:
a[2:3]

array([[ 9, 10, 11, 12]])

In [96]:
a[:,1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [97]:
a[:,2:3]

array([[ 3],
       [ 7],
       [11]])

In [100]:
a[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [101]:
a[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [77]:
a[2,3]

12

In [78]:
a[2,2]

11

In [79]:
a[0,0]

1

In [80]:
print(a)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


# Conctiaton

In [102]:
np.concatenate((b,a))

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [104]:
c=np.hstack((b,a))

# split

In [105]:
c

array([[13, 14, 15, 16,  1,  2,  3,  4],
       [17, 18, 19, 20,  5,  6,  7,  8],
       [21, 22, 23, 24,  9, 10, 11, 12]])

In [106]:
np.split(c,3)

[array([[13, 14, 15, 16,  1,  2,  3,  4]]),
 array([[17, 18, 19, 20,  5,  6,  7,  8]]),
 array([[21, 22, 23, 24,  9, 10, 11, 12]])]

In [107]:
np.split(c,4,axis=1)

[array([[13, 14],
        [17, 18],
        [21, 22]]),
 array([[15, 16],
        [19, 20],
        [23, 24]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [91]:
np.split(c,[2,2])

[array([[13, 14, 15, 16,  1,  2,  3,  4],
        [17, 18, 19, 20,  5,  6,  7,  8]]),
 array([], shape=(0, 8), dtype=int32),
 array([[21, 22, 23, 24,  9, 10, 11, 12]])]

In [92]:
np.split(c,[2,3])

[array([[13, 14, 15, 16,  1,  2,  3,  4],
        [17, 18, 19, 20,  5,  6,  7,  8]]),
 array([[21, 22, 23, 24,  9, 10, 11, 12]]),
 array([], shape=(0, 8), dtype=int32)]

# Sin, cos, sec()

In [99]:
np.sin(0)

0.0

In [100]:
np.tan(90)

-1.995200412208242

# Random

In [3]:
import random

In [53]:
b=np.random.random((5,3))

In [11]:
np.random.randint((5,3))

array([0, 2])

In [52]:
a=np.random.randint(1,4,(5,3))

In [28]:
np.random.seed(1)
np.random.randint(1,4,(5,3))

array([[2, 1, 1],
       [2, 2, 1],
       [1, 2, 1],
       [2, 1, 3],
       [2, 3, 1]])

In [54]:
a+b

array([[3.77838924, 2.71597052, 3.8027575 ],
       [1.09280081, 1.51815255, 3.86502025],
       [1.82914691, 2.82960336, 3.27304997],
       [3.0592432 , 1.67052804, 2.59306552],
       [2.6716541 , 3.41178788, 1.1975509 ]])

In [58]:
np.vstack((a,b))

array([[3.        , 2.        , 3.        ],
       [1.        , 1.        , 3.        ],
       [1.        , 2.        , 3.        ],
       [3.        , 1.        , 2.        ],
       [2.        , 3.        , 1.        ],
       [0.77838924, 0.71597052, 0.8027575 ],
       [0.09280081, 0.51815255, 0.86502025],
       [0.82914691, 0.82960336, 0.27304997],
       [0.0592432 , 0.67052804, 0.59306552],
       [0.6716541 , 0.41178788, 0.1975509 ]])

# String

In [29]:
st1="Hello"
st2='world'

In [30]:
np.char.add(st1,st2)

array('Helloworld', dtype='<U10')

In [31]:
st3=st1+' '+st2
st3

'Hello world'

In [ ]:
np.char.add(st1,st2)

In [33]:
np.char.lower(st3)

array('hello world', dtype='<U11')

In [34]:
np.char.upper(st3)

array('HELLO WORLD', dtype='<U11')

In [ ]:
np.char.lower(st1)

In [ ]:
np.char.upper(st1)

In [35]:
np.char.center(st1,30)

array('            Hello             ', dtype='<U30')

In [41]:
np.char.center(st3,30, fillchar="%")

array('%%%%%%%%%Hello world%%%%%%%%%%', dtype='<U30')

In [51]:
print(np.__version__)

1.19.5


In [47]:
np.char.count((st3),'l')

array(3)

In [50]:
dtype

NameError: name 'dtype' is not defined